services:
  react-app-dev:
    container_name: front-react-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3306:3306'
    volumes:
      - ./src:/app/src:ro
      - ~/ssl:/etc/ssl:ro
    env_file:
      - ./.env.local
    # network_mode: host