version: '3'
services:
  react-app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      # npm run build시 환경 변수 참조가 안되어 args로 전달하고, Dockerfile에서 변수로 사용한다.
      args:
        - REACT_APP_NAME=front
        - REACT_APP_TITLE=duckling
    ports:
      - '80:80'
      # 80: HTTP Port for NGINX Web Server